version: '3.8'
services:
  app:
    restart: unless-stopped
    build: .
    network_mode: "host"
    volumes:
      - .:/usr/src/app
    devices:
      - "/dev/i2c-20:/dev/i2c-20"
      - "/dev/i2c-21:/dev/i2c-21"
    environment:
      - PYTHONUNBUFFERED=1
